// Generated by scripts/gen-piece-css.mjs — DO NOT EDIT. Re-run the script after changing assets/pieces/.

export interface PieceSetDef {
  key: string;
  name: string;
}

export const PIECE_SETS: readonly PieceSetDef[] = [
  { key: "traditional", name: "传统" },
  { key: "letter", name: "字母" },
  { key: "blind", name: "盲棋" },
];
