// Generated by scripts/gen-piece-css.mjs — DO NOT EDIT. Re-run the script after changing assets/pieces/.

export interface PieceSetDef {
  key: string;
  name: string;
}

export const PIECE_SETS: readonly PieceSetDef[] = [
  { key: "traditional", name: "传统" },
  { key: "faction", name: "阵营" },
  { key: "letter", name: "字母" },
  { key: "shapes", name: "图形" },
  { key: "cartoon", name: "卡通" },
  { key: "disguised", name: "盲棋" },
];
